name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0+1
  provider: ^5.0.0
  flutter_switch: ^0.3.1
  intl: ^0.17.0
  dio: ^4.0.0
  enum_to_string: ^2.0.1
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - res/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700