name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.19.3
  provider: ^5.0.0
  flutter_switch: ^0.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Regular.ttf
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
          weight: 700